baseURL: "https://sh3bu.github.io/public/index.html" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Shebu 🔽
paginate: 8
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-T6XL9391MH

minify:
    disableXML: true
    #minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.

    cover:
    responsiveImages: false


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    #comments: true
    images: ["papermod-cover.png"]


    homeInfoParams:
        Title: "Whoami"
        Content: |
            Hey There 👋🏻, I'm **Shebu** - (sh3bu).

            A Security Geek : Building and Breaking for Knowledge
            

            - M.Tech Cybersecurity student at **TIFAC CORE** in Cyber Security - **Amrita Vishwa Vidhyapeetham**.
            - Security Intern at **Philips**.
            - Currently preparing for **Comptia Pentest+**.


    socialIcons:
        - name: github
          url: "https://github.com/sh3bu"
        - name: twitter
          url: "https://twitter.com/_sh3bu"
        - name: linkedin
          url: "https://linkedin.com/shebu"
        - name: instagram
          url: "https://www.instagram.com/_shebu._/"
        - name: tryhackme
          url: "https://tryhackme.com/p/shebu"
        - name: hackthebox
          url: "https://app.hackthebox.com/profile/433595"
        - name: Rss
          url: "index.xml"

    #editPost:
        #URL: "https://github.com/<gitlab user>/<repo name>/tree/<branch name>/<path to content>/"
        #Text: "Suggest Changes" # edit text
        #appendFilePath: true # to append file path to Edit link

outputs:
    home:
        - HTML
        - RSS
        - JSON




    label:
        text: "CTF writeups & more"
        icon: static/gok.jpg
        iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    assets:
     disableHLJS: true
     favicon:  "/favicons/favicon.ico"
     favicon16x16:  /favicons/favicon-16x16.png
     favicon32x32:  /favicons/favicon-32x32.png
     apple_touch_icon:  /favicons/apple-touch-icon.png
     safari_pinned_tab:  /favicons/apple-touch-icon.png


    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    fuseOpts:
         isCaseSensitive: false
         shouldSort: true
         location: 0
         distance: 1000
         threshold: 0.4
         minMatchCharLength: 0
         keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
